// Descarga el catálogo desde free-exercise-db (CC-BY) y genera supabase/seed-data.json
// Uso: npm run seed:fetch
import { writeFile, mkdir } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const OUT = path.join(__dirname, '..', 'supabase', 'seed-data.json')
const SOURCE = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/dist/exercises.json'
const IMG_BASE = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises'

const MUSCLES = {
  abdominals: { name: 'Abdominales', group: 'core' },
  hamstrings: { name: 'Isquiotibiales', group: 'pierna' },
  calves: { name: 'Gemelos', group: 'pierna' },
  shoulders: { name: 'Hombros', group: 'hombros' },
  adductors: { name: 'Aductores', group: 'pierna' },
  glutes: { name: 'Glúteos', group: 'pierna' },
  quadriceps: { name: 'Cuádriceps', group: 'pierna' },
  biceps: { name: 'Bíceps', group: 'brazos' },
  forearms: { name: 'Antebrazos', group: 'brazos' },
  abductors: { name: 'Abductores', group: 'pierna' },
  triceps: { name: 'Tríceps', group: 'brazos' },
  chest: { name: 'Pectorales', group: 'pecho' },
  'lower back': { name: 'Zona lumbar', group: 'espalda' },
  traps: { name: 'Trapecios', group: 'espalda' },
  'middle back': { name: 'Dorsales', group: 'espalda' },
  lats: { name: 'Dorsales', group: 'espalda' },
  neck: { name: 'Cuello', group: 'espalda' },
}

const EQUIPMENT = {
  'body only': { name: 'Peso corporal', kind: 'bodyweight' },
  machine: { name: 'Máquina', kind: 'machine' },
  other: { name: 'Otros', kind: 'other' },
  'foam roll': { name: 'Foam roller', kind: 'other' },
  '': { name: 'Otros', kind: 'other' },
  kettlebells: { name: 'Pesa rusa', kind: 'free_weight' },
  dumbbell: { name: 'Mancuerna', kind: 'free_weight' },
  cable: { name: 'Polea', kind: 'cable' },
  barbell: { name: 'Barra', kind: 'free_weight' },
  bands: { name: 'Banda elástica', kind: 'band' },
  'medicine ball': { name: 'Balón medicinal', kind: 'other' },
  'exercise ball': { name: 'Pelota suiza', kind: 'other' },
  'e-z curl bar': { name: 'Barra Z', kind: 'free_weight' },
}

const CATEGORIES = {
  strength: 'fuerza',
  stretching: 'estiramiento',
  plyometrics: 'pliometria',
  strongman: 'strongman',
  powerlifting: 'powerlifting',
  cardio: 'cardio',
  'olympic weightlifting': 'halterofilia',
}

const LEVELS = { beginner: 'principiante', intermediate: 'intermedio', expert: 'avanzado' }

// Traducciones al español de los ejercicios más comunes (fallback: nombre en inglés)
const TRANSLATIONS = {
  '3/4 sit-up': 'Abdominal 3/4',
  'ab rollout': 'Rueda abdominal',
  'ab wheel rollout': 'Rueda abdominal',
  'alternating dumbbell bench press': 'Press banca alternado con mancuernas',
  'alternating incline dumbbell curl': 'Curl alternado en banco inclinado',
  'alternating kettlebell press': 'Press alternado con pesa rusa',
  'archer pull up': 'Dominada arquería',
  'arnold dumbbell press': 'Press Arnold',
  'arnold press': 'Press Arnold',
  'assisted chin-up': 'Dominada asistida',
  'assisted dip': 'Fondos asistidos',
  'assisted pull-up': 'Dominada asistida',
  'assisted standing triceps extension': 'Extensión de tríceps asistida de pie',
  'atlantis chest press': 'Press de pecho en máquina',
  'back extension': 'Extensiones de espalda',
  'back extension (on exercise ball)': 'Extensiones de espalda con pelota',
  'barbell bench press': 'Press de banca',
  'barbell curl': 'Curl con barra',
  'barbell deadlift': 'Peso muerto',
  'barbell front raise': 'Elevación frontal con barra',
  'barbell glute bridge': 'Puente de glúteos con barra',
  'barbell incline bench press': 'Press inclinado con barra',
  'barbell row': 'Remo con barra',
  'barbell shoulder press': 'Press militar con barra',
  'barbell shrug': 'Encogimientos con barra',
  'barbell squat': 'Sentadilla con barra',
  'barbell triceps extension': 'Extensión de tríceps con barra',
  'bench dip': 'Fondos en banco',
  'bench press': 'Press de banca',
  'bench press - powerlifting': 'Press de banca (powerlifting)',
  'bent over barbell row': 'Remo con barra',
  'bent over dumbbell rear delt raise': 'Pájaros con mancuernas',
  'bent over two-dumbbell row': 'Remo con dos mancuernas',
  'bicycle crunch': 'Bicicleta',
  'bodyweight flyes': 'Aperturas con peso corporal',
  'bodyweight squat': 'Sentadilla con peso corporal',
  'box jump': 'Salto al cajón',
  'box squat': 'Sentadilla en cajón',
  'bulgarian split squat': 'Sentadilla búlgara',
  'burpee': 'Burpee',
  'butterfly': 'Aperturas en máquina (butterfly)',
  'cable crossover': 'Cruces en polea',
  'cable crunch': 'Crunch en polea',
  'cable curl': 'Curl en polea',
  'cable flyes': 'Aperturas en polea',
  'cable hip adduction': 'Aducción de cadera en polea',
  'cable internal rotation': 'Rotación interna en polea',
  'cable lateral raise': 'Elevaciones laterales en polea',
  'cable one arm tricep extension': 'Extensión de tríceps con un brazo en polea',
  'cable rear delt fly': 'Pájaros en polea',
  'cable rope rear-delt rows': 'Remo al mentón con cuerda en polea',
  'cable seated row': 'Remo sentado en polea',
  'cable shrug': 'Encogimientos en polea',
  'cable side bend': 'Flexión lateral en polea',
  'cable triceps pushdown': 'Extensión de tríceps en polea',
  'calf press on the leg press machine': 'Gemelos en prensa',
  'calf raise on a dumbbell': 'Gemelos con mancuerna',
  'calf raises': 'Elevación de gemelos',
  'captains chair straight leg raise': 'Elevación de piernas en silla romana',
  'chin-up': 'Dominada supina',
  'chin-ups': 'Dominada supina',
  'close-grip barbell bench press': 'Press de banca agarre cerrado',
  'close-grip dumbbell press': 'Press con mancuernas agarre cerrado',
  'close-grip ez-bar curl': 'Curl con barra Z agarre cerrado',
  'close-grip ez-bar pressdown': 'Pressdown con barra Z agarre cerrado',
  'close-grip front lat pulldown': 'Jalón al pecho agarre cerrado',
  'concentration curls': 'Curl concentrado',
  'crunch': 'Crunch',
  'crunch (hands overhead)': 'Crunch con manos arriba',
  'crunch - legs on exercise ball': 'Crunch con piernas en pelota',
  'dead bug': 'Insecto muerto',
  'deadlift': 'Peso muerto',
  'decline barbell bench press': 'Press declinado con barra',
  'decline bench press': 'Press declinado',
  'decline crunch': 'Crunch declinado',
  'decline dumbbell bench press': 'Press declinado con mancuernas',
  'decline push-up': 'Flexión declinada',
  'diamond push-up': 'Flexión diamante',
  'dips - chest version': 'Fondos de pecho',
  'dips - triceps version': 'Fondos de tríceps',
  'dumbbell bench press': 'Press de banca con mancuernas',
  'dumbbell bicep curl': 'Curl con mancuernas',
  'dumbbell calf raise': 'Gemelos con mancuernas',
  'dumbbell chest press': 'Press de pecho con mancuernas',
  'dumbbell clean': 'Cargada con mancuernas',
  'dumbbell flyes': 'Aperturas con mancuernas',
  'dumbbell front raise': 'Elevación frontal con mancuernas',
  'dumbbell goblet squat': 'Sentadilla goblet',
  'dumbbell incline bench press': 'Press inclinado con mancuernas',
  'dumbbell incline row': 'Remo inclinado con mancuernas',
  'dumbbell lunge': 'Zancadas con mancuernas',
  'dumbbell lunges': 'Zancadas con mancuernas',
  'dumbbell one-arm shoulder press': 'Press de hombro con un brazo',
  'dumbbell one-arm triceps extension': 'Extensión de tríceps con un brazo',
  'dumbbell rear lunge': 'Zancada inversa con mancuernas',
  'dumbbell row': 'Remo con mancuerna',
  'dumbbell seated one-leg calf raise': 'Gemelos sentado con una pierna',
  'dumbbell shoulder press': 'Press de hombros con mancuernas',
  'dumbbell shrug': 'Encogimientos con mancuernas',
  'dumbbell side bend': 'Flexión lateral con mancuernas',
  'dumbbell step-ups': 'Paso al cajón con mancuernas',
  'dumbbell triceps extension': 'Extensión de tríceps con mancuernas',
  'e-z bar curl': 'Curl con barra Z',
  'ez-bar curl': 'Curl con barra Z',
  'ez-bar skullcrusher': 'Copa con barra Z',
  'ez-bar triceps extension': 'Extensión de tríceps con barra Z',
  'exercise ball crunch': 'Crunch con pelota',
  'exercise ball pull-in': 'Pull-in con pelota',
  'face pull': 'Face pull',
  'farmer\'s walk': 'Paseo del granjero',
  'flat bench cable flyes': 'Aperturas en polea en banco plano',
  'flexor incline cable curl': 'Curl en polea en banco inclinado',
  'floor press': 'Press en el suelo',
  'flutter kicks': 'Patadas de aleteo',
  'front barbell squat': 'Sentadilla frontal',
  'front cable raise': 'Elevación frontal en polea',
  'front dumbbell raise': 'Elevación frontal con mancuernas',
  'front leg raises': 'Elevación de piernas frontal',
  'front squat': 'Sentadilla frontal',
  'full range of motion lat pulldown': 'Jalón al pecho de rango completo',
  'glute bridge': 'Puente de glúteos',
  'glute kickback': 'Patada de glúteos',
  'goblet squat': 'Sentadilla goblet',
  'good-morning': 'Buenos días',
  'hack squat': 'Sentadilla en máquina (hack)',
  'hammer curl': 'Curl martillo',
  'hammer curls': 'Curl martillo',
  'handstand push-up': 'Flexión de pino',
  'hanging leg raise': 'Elevación de piernas colgado',
  'hip abduction machine': 'Máquina de abducción',
  'hip adduction machine': 'Máquina de aducción',
  'hip thrust': 'Empuje de cadera',
  'hip thrust with band': 'Empuje de cadera con banda',
  'hyperextension': 'Hiperextensiones',
  'incline barbell bench press': 'Press inclinado con barra',
  'incline bench press': 'Press inclinado',
  'incline cable curl': 'Curl en polea inclinado',
  'incline dumbbell bench press': 'Press inclinado con mancuernas',
  'incline dumbbell curl': 'Curl inclinado con mancuernas',
  'incline dumbbell flyes': 'Aperturas inclinadas con mancuernas',
  'incline hammer curls': 'Curl martillo inclinado',
  'incline push-up': 'Flexión inclinada',
  'inverted row': 'Remo invertido',
  'jackknife sit-up': 'Navaja',
  'jump rope': 'Saltar la cuerda',
  'jump squat': 'Sentadilla con salto',
  'kettlebell one-leg deadlift': 'Peso muerto a una pierna con pesa rusa',
  'kettlebell swing': 'Balanceo con pesa rusa',
  'kneeling cable crunch': 'Crunch de rodillas en polea',
  'kneeling push-up': 'Flexión de rodillas',
  'knees tucked crunch': 'Crunch con rodillas juntas',
  'landmine press': 'Press en landmine',
  'lat pulldown': 'Jalón al pecho',
  'lat pulldown with rope attachment': 'Jalón con cuerda',
  'lateral raise': 'Elevaciones laterales',
  'leg extension': 'Extensiones de cuádriceps',
  'leg extensions': 'Extensiones de cuádriceps',
  'leg press': 'Prensa de piernas',
  'leg raise': 'Elevación de piernas',
  'lever chest fly': 'Aperturas en máquina',
  'lever deadlift': 'Peso muerto en máquina',
  'lever row': 'Remo en máquina',
  'lever seated row': 'Remo sentado en máquina',
  'lever shoulder press': 'Press de hombros en máquina',
  'low cable triceps extension': 'Extensión de tríceps en polea baja',
  'lower back curl': 'Curl lumbar',
  'lunge': 'Zancada',
  'lunges': 'Zancadas',
  'lying leg curls': 'Curl de piernas acostado',
  'lying triceps press': 'Press de tríceps acostado',
  'machine bench press': 'Press de pecho en máquina',
  'machine bicep curl': 'Curl de bíceps en máquina',
  'machine lateral raise': 'Elevaciones laterales en máquina',
  'machine leg curl': 'Curl de piernas en máquina',
  'machine shoulder press': 'Press de hombros en máquina',
  'machine squat': 'Sentadilla en máquina',
  'machine triceps extension': 'Extensión de tríceps en máquina',
  'middle back shrug': 'Encogimientos de espalda media',
  'military press': 'Press militar',
  'mixed grip chin-up': 'Dominada con agarre mixto',
  'mountain climbers': 'Escalador',
  'muscle-up': 'Muscle up',
  'narrow stance hack squats': 'Sentadilla hack con postura estrecha',
  'neutral grip dumbbell shoulder press': 'Press de hombros neutro con mancuernas',
  'one arm dumbbell bench press': 'Press de banca con un brazo',
  'one-arm dumbbell row': 'Remo con mancuerna a un brazo',
  'one-arm kettlebell clean': 'Cargada con pesa rusa a un brazo',
  'one-arm kettlebell military press': 'Press militar con pesa rusa a un brazo',
  'one-arm kettlebell row': 'Remo con pesa rusa a un brazo',
  'one-arm long bar row': 'Remo con barra larga a un brazo',
  'one-arm smith machine row': 'Remo a un brazo en máquina Smith',
  'one-legged cable kickback': 'Patada de glúteos a una pierna en polea',
  'overhead squat': 'Sentadilla por encima de la cabeza',
  'overhead triceps extension': 'Extensión de tríceps sobre la cabeza',
  'palms-down wrist curl over a bench': 'Curl de muñeca con palmas abajo',
  'palms-up wrist curl over a bench': 'Curl de muñeca con palmas arriba',
  'pec deck flyes': 'Aperturas en máquina (pec deck)',
  'pelvic tilt into bridge': 'Puente pélvico',
  'performing a triceps pressdown': 'Pressdown de tríceps',
  'pike push-up': 'Flexión de pico',
  'pistol squat': 'Sentadilla pistola',
  'plank': 'Plancha',
  'plate pinch': 'Pinza de discos',
  'plate push': 'Empuje de disco',
  'power clean': 'Cargada de potencia',
  'power snatch': 'Arrancada de potencia',
  'power shrug': 'Encogimiento de potencia',
  'preacher curl': 'Curl en banco Scott',
  'press sit-up': 'Press con crunch',
  'pull-up': 'Dominada',
  'pull-ups': 'Dominadas',
  'push press': 'Push press',
  'push-up': 'Flexión',
  'push-up on medicine ball': 'Flexión sobre balón medicinal',
  'push-ups with feet elevated': 'Flexión con pies elevados',
  'pushups': 'Flexiones',
  'quasi pushup': 'Flexión parcial',
  'rear pull-up': 'Dominada trasera',
  'rear-delt cable row': 'Remo de deltoides posterior en polea',
  'resistance band leg press': 'Prensa de piernas con banda',
  'reverse band bench press': 'Press de banca con banda',
  'reverse barbell curl': 'Curl inverso con barra',
  'reverse cable curl': 'Curl inverso en polea',
  'reverse crunch': 'Crunch inverso',
  'reverse dumbbell curl': 'Curl inverso con mancuernas',
  'reverse flyes': 'Pájaros inversos',
  'reverse flyes with external rotation': 'Pájaros inversos con rotación',
  'reverse grip lat pulldown': 'Jalón al pecho agarre supino',
  'reverse-grip pushdown': 'Pressdown agarre supino',
  'reverse hyperextension': 'Hiperextensión inversa',
  'reverse wrist curl': 'Curl de muñeca inverso',
  'romanian deadlift': 'Peso muerto rumano',
  'rope climbing': 'Escalada de cuerda',
  'rope crunch': 'Crunch con cuerda',
  'rope pushdown': 'Pressdown con cuerda',
  'rotation with plate': 'Rotación con disco',
  'russian twist': 'Giros rusos',
  'scapular pull-up': 'Dominada escapular',
  'seated barbell military press': 'Press militar sentado con barra',
  'seated cable curl': 'Curl sentado en polea',
  'seated cable rows': 'Remo sentado en polea',
  'seated calf raise': 'Gemelos sentado',
  'seated dumbbell curl': 'Curl sentado con mancuernas',
  'seated dumbbell inner biceps curl': 'Curl interno sentado con mancuernas',
  'seated dumbbell press': 'Press sentado con mancuernas',
  'seated dumbbell shoulder press': 'Press de hombros sentado con mancuernas',
  'seated leg curl': 'Curl de piernas sentado',
  'seated leg raise': 'Elevación de piernas sentado',
  'seated one-arm cable row': 'Remo a un brazo sentado en polea',
  'seated one-arm dumbbell palm-in wrist curl': 'Curl de muñeca sentado a un brazo',
  'seated palms-down wrist curl': 'Curl de muñeca sentado palmas abajo',
  'seated palms-up barbell wrist curl': 'Curl de muñeca sentado palmas arriba',
  'seated palms-up wrist curl': 'Curl de muñeca sentado palmas arriba',
  'seated triceps press': 'Press de tríceps sentado',
  'shoulder press': 'Press de hombros',
  'shoulder shrugs': 'Encogimientos de hombros',
  'side lateral raise': 'Elevaciones laterales',
  'side leg raises': 'Elevación lateral de pierna',
  'side plank': 'Plancha lateral',
  'side wrist pull': 'Tracción lateral de muñeca',
  'single-arm cable crossover': 'Cruce en polea con un brazo',
  'single-arm horizontal cable crossover': 'Cruce horizontal en polea con un brazo',
  'single-leg hip thrust': 'Empuje de cadera a una pierna',
  'single-leg lunge': 'Zancada a una pierna',
  'single-leg squat': 'Sentadilla a una pierna',
  'sit-up': 'Abdominal clásico',
  'sit-ups': 'Abdominales clásicos',
  'skullcrusher': 'Copa',
  'sled drag - harness': 'Arrastre de trineo con arnés',
  'sled overhead backward walk': 'Caminata inversa con trineo sobre la cabeza',
  'sled pull - harness': 'Tracción de trineo con arnés',
  'smith machine bench press': 'Press de banca en máquina Smith',
  'smith machine bent knee hip thrust': 'Empuje de cadera en Smith',
  'smith machine calf raise': 'Gemelos en Smith',
  'smith machine close-grip bench press': 'Press cerrado en Smith',
  'smith machine incline bench press': 'Press inclinado en Smith',
  'smith machine leg press': 'Prensa en Smith',
  'smith machine one-arm upright row': 'Remo vertical a un brazo en Smith',
  'smith machine shrug': 'Encogimientos en Smith',
  'smith machine squat': 'Sentadilla en Smith',
  'smith machine stiff-legged deadlift': 'Peso muerto piernas rígidas en Smith',
  'smith machine upright row': 'Remo vertical en Smith',
  'smith single-leg split squat': 'Sentadilla dividida en Smith',
  'snatch': 'Arrancada',
  'snatch-grip deadlift': 'Peso muerto agarre arrancada',
  'spider curl': 'Curl araña',
  'standing barbell calf raise': 'Gemelos de pie con barra',
  'standing barbell press behind neck': 'Press tras nuca con barra',
  'standing bent-over two-arm dumbbell row': 'Remo con dos mancuernas',
  'standing calf raises': 'Gemelos de pie',
  'standing calf stretch': 'Estiramiento de gemelos de pie',
  'standing concentration curl': 'Curl concentrado de pie',
  'standing dumbbell calf raise': 'Gemelos de pie con mancuernas',
  'standing dumbbell press': 'Press de pie con mancuernas',
  'standing dumbbell straight-arm front delt raise': 'Elevación frontal con mancuernas',
  'standing dumbbell triceps extension': 'Extensión de tríceps de pie con mancuernas',
  'standing lateral raise': 'Elevaciones laterales de pie',
  'standing leg raise': 'Elevación de piernas de pie',
  'standing low-pulley deltoid raise': 'Elevación de deltoides en polea baja',
  'standing one-arm cable curl': 'Curl a un brazo en polea',
  'standing palmar press barbell press': 'Press de pie con barra',
  'standing reverse barbell curl': 'Curl inverso de pie con barra',
  'standing rope crunch': 'Crunch de pie con cuerda',
  'standing shrug': 'Encogimientos de pie',
  'standing sumo stiff-leg deadlift': 'Peso muerto sumo piernas rígidas',
  'standing toe touches': 'Toques de pies de pie',
  'stationary bike': 'Bicicleta fija',
  'step-up with knee raise': 'Paso al cajón con elevación de rodilla',
  'step-ups': 'Pasos al cajón',
  'stiff-leg barbell deadlift': 'Peso muerto piernas rígidas',
  'straight-arm pulldown': 'Jalón con brazos rectos',
  'stretch': 'Estiramiento',
  'sumo deadlift': 'Peso muerto sumo',
  'superman': 'Superman',
  'suspended push-up': 'Flexión suspendida',
  't-bar row': 'Remo T',
  'thigh abductor': 'Abductores',
  'thigh adductor': 'Aductores',
  'towel crunch': 'Crunch con toalla',
  'trap bar deadlift': 'Peso muerto con barra trampa',
  'triceps pushdown': 'Pressdown de tríceps',
  'triceps pushdown - rope attachment': 'Pressdown de tríceps con cuerda',
  'triceps pushdown - v-bar attachment': 'Pressdown de tríceps con V',
  'turkish get-up': 'Levantamiento turco',
  'twisting crunch': 'Crunch con giro',
  'upright barbell row': 'Remo vertical con barra',
  'upright row': 'Remo vertical',
  'v-bar pulldown': 'Jalón con V',
  'v-bar seated row': 'Remo sentado con V',
  'v-up': 'V-up',
  'walking lunge': 'Zancada caminando',
  'weighted crunch': 'Crunch con peso',
  'weighted pull-up': 'Dominada con peso',
  'weighted sit-up': 'Abdominal con peso',
  'wide-grip barbell bench press': 'Press de banca agarre ancho',
  'wide-grip lat pulldown': 'Jalón al pecho agarre ancho',
  'wide-grip pull-up': 'Dominada agarre ancho',
  'wide-grip rear pull-up': 'Dominada trasera agarre ancho',
  'wide-grip standing barbell curl': 'Curl con barra agarre ancho',
  'windmill': 'Molino',
  'wrist roller': 'Rodillo de muñeca',
  'zercher squat': 'Sentadilla Zercher',
  'zottman curl': 'Curl Zottman',
}

// Traducción completa del resto del catálogo (701 ejercicios)
const EXTRA_TRANSLATIONS = {
  '90/90 hamstring': 'Estiramiento de isquios 90/90',
  'ab crunch machine': 'Máquina de abdominales',
  'ab roller': 'Rueda abdominal',
  'adductor': 'Aductor',
  'adductor/groin': 'Aductor/ingle',
  'advanced kettlebell windmill': 'Molino con pesa rusa (avanzado)',
  'air bike': 'Bicicleta aérea',
  'all fours quad stretch': 'Estiramiento de cuádriceps en cuatro patas',
  'alternate hammer curl': 'Curl martillo alternado',
  'alternate heel touchers': 'Toques de talón alternados',
  'alternate incline dumbbell curl': 'Curl inclinado alternado con mancuernas',
  'alternate leg diagonal bound': 'Saltos diagonales alternados',
  'alternating cable shoulder press': 'Press de hombros alternado en polea',
  'alternating deltoid raise': 'Elevación de deltoides alternada',
  'alternating floor press': 'Press en el suelo alternado',
  'alternating hang clean': 'Cargada colgado alternada',
  'alternating kettlebell row': 'Remo alternado con pesa rusa',
  'alternating renegade row': 'Remo renegado alternado',
  'ankle circles': 'Círculos de tobillo',
  'ankle on the knee': 'Tobillo sobre rodilla',
  'anterior tibialis-smr': 'Tibial anterior - liberación miofascial',
  'anti-gravity press': 'Press antigravedad',
  'arm circles': 'Círculos de brazos',
  'around the worlds': 'Círculos con mancuernas (around the world)',
  'atlas stone trainer': 'Entrenador de piedra de Atlas',
  'atlas stones': 'Piedras de Atlas',
  'axle deadlift': 'Peso muerto con barra gruesa',
  'back flyes - with bands': 'Pájaros de espalda con bandas',
  'backward drag': 'Arrastre hacia atrás',
  'backward medicine ball throw': 'Lanzamiento de balón medicinal hacia atrás',
  'balance board': 'Tabla de equilibrio',
  'ball leg curl': 'Curl de piernas con pelota',
  'band assisted pull-up': 'Dominada asistida con banda',
  'band good morning': 'Buenos días con banda',
  'band good morning (pull through)': 'Buenos días con banda (pull through)',
  'band hip adductions': 'Aducciones de cadera con banda',
  'band pull apart': 'Aperturas con banda',
  'band skull crusher': 'Copa con banda',
  'barbell ab rollout': 'Rueda abdominal con barra',
  'barbell ab rollout - on knees': 'Rueda abdominal con barra de rodillas',
  'barbell bench press - medium grip': 'Press de banca agarre medio',
  'barbell curls lying against an incline': 'Curl con barra acostado en banco inclinado',
  'barbell full squat': 'Sentadilla completa con barra',
  'barbell guillotine bench press': 'Press de banca guillotina',
  'barbell hack squat': 'Hack squat con barra',
  'barbell hip thrust': 'Empuje de cadera con barra',
  'barbell incline bench press - medium grip': 'Press inclinado con barra agarre medio',
  'barbell incline shoulder raise': 'Elevación de hombros inclinada con barra',
  'barbell lunge': 'Zancada con barra',
  'barbell rear delt row': 'Remo de deltoides posterior con barra',
  'barbell rollout from bench': 'Rueda abdominal con barra desde banco',
  'barbell seated calf raise': 'Gemelos sentado con barra',
  'barbell shrug behind the back': 'Encogimientos con barra detrás',
  'barbell side bend': 'Flexión lateral con barra',
  'barbell side split squat': 'Sentadilla dividida lateral con barra',
  'barbell squat to a bench': 'Sentadilla con barra hasta el banco',
  'barbell step ups': 'Pasos al cajón con barra',
  'barbell walking lunge': 'Zancada caminando con barra',
  'battling ropes': 'Cuerda de batalla',
  'bear crawl sled drags': 'Arrastre de trineo a cuatro patas',
  'behind head chest stretch': 'Estiramiento de pecho detrás de la cabeza',
  'bench dips': 'Fondos en banco',
  'bench jump': 'Salto al banco',
  'bench press - with bands': 'Press de banca con bandas',
  'bench press with chains': 'Press de banca con cadenas',
  'bench sprint': 'Sprint en banco',
  'bent-arm barbell pullover': 'Pullover con barra brazos flexionados',
  'bent-arm dumbbell pullover': 'Pullover con mancuerna brazos flexionados',
  'bent-knee hip raise': 'Elevación de cadera con rodillas flexionadas',
  'bent over dumbbell rear delt raise with head on bench': 'Pájaros con mancuernas apoyando la cabeza',
  'bent over low-pulley side lateral': 'Elevación lateral en polea baja',
  'bent over one-arm long bar row': 'Remo a un brazo con barra larga',
  'bent over two-arm long bar row': 'Remo con barra larga',
  'bent over two-dumbbell row with palms in': 'Remo con dos mancuernas palmas hacia dentro',
  'bent press': 'Press inclinado',
  'bicycling': 'Bicicleta',
  'bicycling, stationary': 'Bicicleta fija',
  'board press': 'Press con tablas',
  'body-up': 'Subida corporal',
  'body tricep press': 'Press de tríceps con peso corporal',
  'bodyweight mid row': 'Remo medio con peso corporal',
  'bodyweight walking lunge': 'Zancada caminando con peso corporal',
  'bosu ball cable crunch with side bends': 'Crunch en BOSU con flexiones laterales en polea',
  'bottoms-up clean from the hang position': 'Cargada desde colgado con disco arriba',
  'bottoms up': 'Bottoms up',
  'box jump (multiple response)': 'Salto al cajón (respuesta múltiple)',
  'box skip': 'Saltos al cajón alternados',
  'box squat with bands': 'Sentadilla en cajón con bandas',
  'box squat with chains': 'Sentadilla en cajón con cadenas',
  'brachialis-smr': 'Braquial - liberación miofascial',
  'bradford/rocky presses': 'Press Bradford',
  'butt-ups': 'Elevación de caderas',
  'butt lift (bridge)': 'Puente de glúteos',
  'cable chest press': 'Press de pecho en polea',
  'cable deadlifts': 'Peso muerto en polea',
  'cable hammer curls - rope attachment': 'Curl martillo en polea con cuerda',
  'cable incline pushdown': 'Pressdown inclinado en polea',
  'cable incline triceps extension': 'Extensión de tríceps inclinada en polea',
  'cable iron cross': 'Cruz de hierro en polea',
  'cable judo flip': 'Giro de judo en polea',
  'cable lying triceps extension': 'Extensión de tríceps acostado en polea',
  'cable preacher curl': 'Curl en banco Scott con polea',
  'cable reverse crunch': 'Crunch inverso en polea',
  'cable rope overhead triceps extension': 'Extensión de tríceps sobre la cabeza con cuerda',
  'cable russian twists': 'Giros rusos en polea',
  'cable seated crunch': 'Crunch sentado en polea',
  'cable seated lateral raise': 'Elevación lateral sentado en polea',
  'cable shoulder press': 'Press de hombros en polea',
  'cable shrugs': 'Encogimientos en polea',
  'cable wrist curl': 'Curl de muñeca en polea',
  'calf-machine shoulder shrug': 'Encogimientos en máquina de gemelos',
  'calf press': 'Prensa de gemelos',
  'calf raises - with bands': 'Gemelos con bandas',
  'calf stretch elbows against wall': 'Estiramiento de gemelos con codos en la pared',
  'calf stretch hands against wall': 'Estiramiento de gemelos con manos en la pared',
  'calves-smr': 'Gemelos - liberación miofascial',
  'car deadlift': 'Peso muerto de coche',
  'car drivers': 'Conductor de coche',
  'carioca quick step': 'Pasos cruzados rápidos',
  'cat stretch': 'Estiramiento de gato',
  'catch and overhead throw': 'Recepción y lanzamiento sobre la cabeza',
  'chain handle extension': 'Extensión con cadena',
  'chain press': 'Press con cadenas',
  'chair leg extended stretch': 'Estiramiento de pierna extendida en silla',
  'chair lower back stretch': 'Estiramiento lumbar en silla',
  'chair squat': 'Sentadilla en silla',
  'chair upper body stretch': 'Estiramiento de torso en silla',
  'chest and front of shoulder stretch': 'Estiramiento de pecho y hombro frontal',
  'chest push from 3 point stance': 'Empuje de pecho desde posición de tres puntos',
  'chest push (multiple response)': 'Empuje de pecho (respuesta múltiple)',
  'chest push (single response)': 'Empuje de pecho (respuesta única)',
  'chest push with run release': 'Empuje de pecho con arranque de carrera',
  'chest stretch on stability ball': 'Estiramiento de pecho sobre pelota suiza',
  "child's pose": 'Postura del niño',
  'chin to chest stretch': 'Estiramiento de cuello (mentón al pecho)',
  'circus bell': 'Pesa de circo',
  'clean': 'Cargada',
  'clean deadlift': 'Peso muerto de cargada',
  'clean pull': 'Tirón de cargada',
  'clean shrug': 'Encogimiento de cargada',
  'clean and jerk': 'Cargada y envión',
  'clean and press': 'Cargada y press',
  'clean from blocks': 'Cargada desde bloques',
  'clock push-up': 'Flexión de reloj',
  'close-grip ez-bar curl with band': 'Curl con barra Z agarre cerrado con banda',
  'close-grip ez-bar press': 'Press con barra Z agarre cerrado',
  'close-grip ez bar curl': 'Curl con barra Z agarre cerrado',
  'close-grip push-up off of a dumbbell': 'Flexión agarre cerrado sobre mancuerna',
  'close-grip standing barbell curl': 'Curl de pie con barra agarre cerrado',
  'cocoons': 'Capullos',
  "conan's wheel": 'Rueda de Conan',
  'cross-body crunch': 'Crunch cruzado',
  'cross body hammer curl': 'Curl martillo cruzado',
  'cross over - with bands': 'Cruces con bandas',
  'crossover reverse lunge': 'Zancada inversa cruzada',
  'crucifix': 'Crucifijo',
  'crunch - hands overhead': 'Crunch con manos sobre la cabeza',
  'crunches': 'Crunch',
  'cuban press': 'Press cubano',
  "dancer's stretch": 'Estiramiento de bailarina',
  'deadlift with bands': 'Peso muerto con bandas',
  'deadlift with chains': 'Peso muerto con cadenas',
  'decline close-grip bench to skull crusher': 'Press cerrado a copa en banco declinado',
  'decline dumbbell flyes': 'Aperturas declinadas con mancuernas',
  'decline dumbbell triceps extension': 'Extensión de tríceps declinada con mancuernas',
  'decline ez bar triceps extension': 'Extensión de tríceps declinada con barra Z',
  'decline oblique crunch': 'Crunch oblicuo declinado',
  'decline reverse crunch': 'Crunch inverso declinado',
  'decline smith press': 'Press declinado en Smith',
  'deficit deadlift': 'Peso muerto con déficit',
  'depth jump leap': 'Salto de profundidad',
  'dip machine': 'Máquina de fondos',
  'donkey calf raises': 'Gemelos de burro',
  'double kettlebell alternating hang clean': 'Cargada colgado alternada con dos pesas rusas',
  'double kettlebell jerk': 'Envión con dos pesas rusas',
  'double kettlebell push press': 'Push press con dos pesas rusas',
  'double kettlebell snatch': 'Arrancada con dos pesas rusas',
  'double kettlebell windmill': 'Molino con dos pesas rusas',
  'double leg butt kick': 'Patada a glúteos con dos piernas',
  'downward facing balance': 'Equilibrio mirando hacia abajo',
  'drag curl': 'Curl de arrastre',
  'drop push': 'Flexión con caída',
  'dumbbell alternate bicep curl': 'Curl de bíceps alternado con mancuernas',
  'dumbbell bench press with neutral grip': 'Press de banca neutro con mancuernas',
  'dumbbell floor press': 'Press en el suelo con mancuernas',
  'dumbbell incline shoulder raise': 'Elevación de hombros inclinada con mancuernas',
  'dumbbell lying one-arm rear lateral raise': 'Elevación posterior acostado a un brazo',
  'dumbbell lying pronation': 'Pronación acostado con mancuerna',
  'dumbbell lying rear lateral raise': 'Elevación posterior acostado con mancuernas',
  'dumbbell lying supination': 'Supinación acostado con mancuerna',
  'dumbbell one-arm upright row': 'Remo vertical a un brazo con mancuerna',
  'dumbbell prone incline curl': 'Curl boca abajo en banco inclinado',
  'dumbbell raise': 'Elevación con mancuernas',
  'dumbbell scaption': 'Elevación escapular con mancuernas',
  'dumbbell seated box jump': 'Salto al cajón sentado con mancuernas',
  'dumbbell squat': 'Sentadilla con mancuernas',
  'dumbbell squat to a bench': 'Sentadilla con mancuernas hasta el banco',
  'dumbbell step ups': 'Pasos al cajón con mancuernas',
  'dumbbell tricep extension -pronated grip': 'Extensión de tríceps pronada con mancuernas',
  'dynamic back stretch': 'Estiramiento dinámico de espalda',
  'dynamic chest stretch': 'Estiramiento dinámico de pecho',
  'elbow circles': 'Círculos de codo',
  'elbow to knee': 'Codo a rodilla',
  'elbows back': 'Coditos hacia atrás',
  'elevated back lunge': 'Zancada inversa elevada',
  'elevated cable rows': 'Remo elevado en polea',
  'elliptical trainer': 'Elíptica',
  'extended range one-arm kettlebell floor press': 'Press en el suelo con pesa rusa a un brazo',
  'external rotation': 'Rotación externa',
  'external rotation with band': 'Rotación externa con banda',
  'external rotation with cable': 'Rotación externa en polea',
  'fast skipping': 'Skipping rápido',
  'finger curls': 'Curl de dedos',
  'flat bench leg pull-in': 'Pull-in de piernas en banco plano',
  'flat bench lying leg raise': 'Elevación de piernas acostado en banco',
  'flexor incline dumbbell curls': 'Curl inclinado flexor con mancuernas',
  'floor glute-ham raise': 'Elevación de glúteos e isquios en el suelo',
  'floor press with chains': 'Press en el suelo con cadenas',
  'foot-smr': 'Pie - liberación miofascial',
  'forward drag with press': 'Arrastre hacia adelante con press',
  'frankenstein squat': 'Sentadilla Frankenstein',
  'freehand jump squat': 'Sentadilla con salto a manos libres',
  'frog hops': 'Saltos de rana',
  'frog sit-ups': 'Abdominales de rana',
  'front barbell squat to a bench': 'Sentadilla frontal con barra hasta el banco',
  'front box jump': 'Salto frontal al cajón',
  'front cone hops (or hurdle hops)': 'Saltos frontales sobre conos',
  'front incline dumbbell raise': 'Elevación frontal inclinada con mancuernas',
  'front plate raise': 'Elevación frontal con disco',
  'front raise and pullover': 'Elevación frontal y pullover',
  'front squat (clean grip)': 'Sentadilla frontal (agarre cargada)',
  'front squats with two kettlebells': 'Sentadilla frontal con dos pesas rusas',
  'front two-dumbbell raise': 'Elevación frontal con dos mancuernas',
  'full range-of-motion lat pulldown': 'Jalón al pecho de rango completo',
  'gironda sternum chins': 'Dominadas Gironda',
  'glute ham raise': 'Elevación de glúteos e isquios',
  'good morning': 'Buenos días',
  'good morning off pins': 'Buenos días desde soportes',
  'gorilla chin/crunch': 'Dominada/crunch gorila',
  'groin and back stretch': 'Estiramiento de ingle y espalda',
  'groiners': 'Abridor de ingle',
  'hammer grip incline db bench press': 'Press inclinado neutro con mancuernas',
  'hamstring-smr': 'Isquios - liberación miofascial',
  'hamstring stretch': 'Estiramiento de isquios',
  'handstand push-ups': 'Flexión de pino',
  'hang clean': 'Cargada colgado',
  'hang clean - below the knees': 'Cargada colgado bajo las rodillas',
  'hang snatch': 'Arrancada colgado',
  'hang snatch - below knees': 'Arrancada colgado bajo las rodillas',
  'hanging bar good morning': 'Buenos días colgado de la barra',
  'hanging pike': 'Pica colgado',
  'heaving snatch balance': 'Equilibrio de arrancada con balanceo',
  'heavy bag thrust': 'Empuje de saco pesado',
  'high cable curls': 'Curl en polea alta',
  'hip circles (prone)': 'Círculos de cadera (boca abajo)',
  'hip extension with bands': 'Extensión de cadera con bandas',
  'hip flexion with band': 'Flexión de cadera con banda',
  'hip lift with band': 'Elevación de cadera con banda',
  'hug a ball': 'Abrazar una pelota',
  'hug knees to chest': 'Abrazo de rodillas al pecho',
  'hurdle hops': 'Saltos de vallas',
  'hyperextensions (back extensions)': 'Hiperextensiones',
  'hyperextensions with no hyperextension bench': 'Hiperextensiones sin banco',
  'it band and glute stretch': 'Estiramiento de banda iliotibial y glúteo',
  'iliotibial tract-smr': 'Banda iliotibial - liberación miofascial',
  'inchworm': 'Oruga',
  'incline barbell triceps extension': 'Extensión de tríceps inclinada con barra',
  'incline bench pull': 'Remo en banco inclinado',
  'incline cable chest press': 'Press de pecho inclinado en polea',
  'incline cable flye': 'Aperturas inclinadas en polea',
  'incline dumbbell bench with palms facing in': 'Press inclinado con mancuernas palmas hacia dentro',
  'incline dumbbell flyes - with a twist': 'Aperturas inclinadas con mancuernas con giro',
  'incline dumbbell press': 'Press inclinado con mancuernas',
  'incline inner biceps curl': 'Curl interno inclinado',
  'incline push-up close-grip': 'Flexión inclinada agarre cerrado',
  'incline push-up depth jump': 'Flexión inclinada con salto de profundidad',
  'incline push-up medium': 'Flexión inclinada media',
  'incline push-up reverse grip': 'Flexión inclinada agarre inverso',
  'incline push-up wide': 'Flexión inclinada agarre ancho',
  'intermediate groin stretch': 'Estiramiento de ingle intermedio',
  'intermediate hip flexor and quad stretch': 'Estiramiento de flexores de cadera y cuádriceps',
  'internal rotation with band': 'Rotación interna con banda',
  'inverted row with straps': 'Remo invertido con anillas',
  'iron cross': 'Cruz de hierro',
  'iron crosses (stretch)': 'Cruces de hierro (estiramiento)',
  'isometric chest squeezes': 'Apretón isométrico de pecho',
  'isometric neck exercise - front and back': 'Ejercicio isométrico de cuello frontal y posterior',
  'isometric neck exercise - sides': 'Ejercicio isométrico de cuello lateral',
  'isometric wipers': 'Limpiaparabrisas isométricos',
  'jm press': 'Press JM',
  'janda sit-up': 'Abdominal Janda',
  'jefferson squats': 'Sentadilla Jefferson',
  'jerk balance': 'Equilibrio de envión',
  'jerk dip squat': 'Media sentadilla de envión',
  'jogging, treadmill': 'Trotar en cinta',
  'keg load': 'Carga de barril',
  'kettlebell arnold press': 'Press Arnold con pesa rusa',
  'kettlebell dead clean': 'Cargada muerta con pesa rusa',
  'kettlebell figure 8': 'Ocho con pesa rusa',
  'kettlebell hang clean': 'Cargada colgado con pesa rusa',
  'kettlebell one-legged deadlift': 'Peso muerto a una pierna con pesa rusa',
  'kettlebell pass between the legs': 'Pase de pesa rusa entre las piernas',
  'kettlebell pirate ships': 'Barco pirata con pesa rusa',
  'kettlebell pistol squat': 'Sentadilla pistola con pesa rusa',
  'kettlebell seated press': 'Press sentado con pesa rusa',
  'kettlebell seesaw press': 'Press balancín con pesa rusa',
  'kettlebell sumo high pull': 'Remo alto sumo con pesa rusa',
  'kettlebell thruster': 'Thruster con pesa rusa',
  'kettlebell turkish get-up (lunge style)': 'Levantamiento turco (estilo zancada)',
  'kettlebell turkish get-up (squat style)': 'Levantamiento turco (estilo sentadilla)',
  'kettlebell windmill': 'Molino con pesa rusa',
  'kipping muscle up': 'Muscle up con balanceo',
  'knee across the body': 'Rodilla cruzando el cuerpo',
  'knee circles': 'Círculos de rodilla',
  'knee/hip raise on parallel bars': 'Elevación de rodillas/cadera en paralelas',
  'knee tuck jump': 'Salto con rodillas al pecho',
  'kneeling arm drill': 'Ejercicio de brazos de rodillas',
  'kneeling cable crunch with alternating oblique twists': 'Crunch de rodillas en polea con giros alternados',
  'kneeling cable triceps extension': 'Extensión de tríceps de rodillas en polea',
  'kneeling forearm stretch': 'Estiramiento de antebrazo de rodillas',
  'kneeling high pulley row': 'Remo de rodillas en polea alta',
  'kneeling hip flexor': 'Flexor de cadera de rodillas',
  'kneeling jump squat': 'Sentadilla con salto de rodillas',
  'kneeling single-arm high pulley row': 'Remo a un brazo de rodillas en polea alta',
  'kneeling squat': 'Sentadilla de rodillas',
  "landmine 180's": 'Giros de 180 en landmine',
  'landmine linear jammer': 'Empuje lineal en landmine',
  'lateral bound': 'Saltos laterales',
  'lateral box jump': 'Salto lateral al cajón',
  'lateral cone hops': 'Saltos laterales sobre conos',
  'lateral raise - with bands': 'Elevaciones laterales con bandas',
  'latissimus dorsi-smr': 'Dorsales - liberación miofascial',
  'leg-over floor press': 'Press en el suelo con pierna cruzada',
  'leg-up hamstring stretch': 'Estiramiento de isquios con pierna elevada',
  'leg lift': 'Elevación de pierna',
  'leg pull-in': 'Pull-in de piernas',
  'leverage chest press': 'Press de pecho en máquina palanca',
  'leverage deadlift': 'Peso muerto en máquina palanca',
  'leverage decline chest press': 'Press declinado en máquina palanca',
  'leverage high row': 'Remo alto en máquina palanca',
  'leverage incline chest press': 'Press inclinado en máquina palanca',
  'leverage iso row': 'Remo isométrico en máquina palanca',
  'leverage shoulder press': 'Press de hombros en máquina palanca',
  'leverage shrug': 'Encogimientos en máquina palanca',
  'linear 3-part start technique': 'Técnica de salida lineal en 3 partes',
  'linear acceleration wall drill': 'Ejercicio de aceleración lineal contra la pared',
  'linear depth jump': 'Salto de profundidad lineal',
  'log lift': 'Levantamiento de tronco',
  'london bridges': 'Puentes de Londres',
  'looking at ceiling': 'Mirando al techo',
  'low cable crossover': 'Cruces en polea baja',
  'low pulley row to neck': 'Remo en polea baja al cuello',
  'lower back-smr': 'Lumbar - liberación miofascial',
  'lunge pass through': 'Zancada con pase',
  'lunge sprint': 'Zancada con sprint',
  'lying bent leg groin': 'Ingle acostado con pierna flexionada',
  'lying cable curl': 'Curl acostado en polea',
  'lying cambered barbell row': 'Remo acostado con barra curvada',
  'lying close-grip bar curl on high pulley': 'Curl acostado agarre cerrado en polea alta',
  'lying close-grip barbell triceps extension behind the head': 'Extensión de tríceps acostado sobre la cabeza',
  'lying close-grip barbell triceps press to chin': 'Press de tríceps acostado al mentón',
  'lying crossover': 'Cruce acostado',
  'lying dumbbell tricep extension': 'Extensión de tríceps acostado con mancuernas',
  'lying face down plate neck resistance': 'Resistencia de cuello con disco boca abajo',
  'lying face up plate neck resistance': 'Resistencia de cuello con disco boca arriba',
  'lying glute': 'Glúteo acostado',
  'lying hamstring': 'Isquios acostado',
  'lying high bench barbell curl': 'Curl con barra en banco alto',
  'lying machine squat': 'Sentadilla acostado en máquina',
  'lying one-arm lateral raise': 'Elevación lateral acostado a un brazo',
  'lying prone quadriceps': 'Cuádriceps boca abajo',
  'lying rear delt raise': 'Elevación de deltoides posterior acostado',
  'lying supine dumbbell curl': 'Curl con mancuernas boca arriba',
  'lying t-bar row': 'Remo T acostado',
  'machine preacher curls': 'Curl en banco Scott en máquina',
  'machine shoulder (military) press': 'Press militar en máquina',
  'medicine ball chest pass': 'Pase de pecho con balón medicinal',
  'medicine ball full twist': 'Giro completo con balón medicinal',
  'medicine ball scoop throw': 'Lanzamiento de cuchara con balón medicinal',
  'middle back stretch': 'Estiramiento de espalda media',
  'mixed grip chin': 'Dominada agarre mixto',
  'monster walk': 'Caminata de monstruo',
  'moving claw series': 'Serie de garra en movimiento',
  'muscle snatch': 'Arrancada muscle',
  'muscle up': 'Muscle up',
  'narrow stance leg press': 'Prensa con postura estrecha',
  'narrow stance squats': 'Sentadilla con postura estrecha',
  'natural glute ham raise': 'Elevación natural de glúteos e isquios',
  'neck-smr': 'Cuello - liberación miofascial',
  'neck press': 'Press de cuello',
  'oblique crunches': 'Crunch oblicuo',
  'oblique crunches - on the floor': 'Crunch oblicuo en el suelo',
  'olympic squat': 'Sentadilla olímpica',
  'on-your-back quad stretch': 'Estiramiento de cuádriceps boca arriba',
  'on your side quad stretch': 'Estiramiento de cuádriceps de lado',
  'one-arm flat bench dumbbell flye': 'Aperturas a un brazo en banco plano',
  'one-arm high-pulley cable side bends': 'Flexiones laterales a un brazo en polea alta',
  'one-arm incline lateral raise': 'Elevación lateral inclinada a un brazo',
  'one-arm kettlebell clean and jerk': 'Cargada y envión con pesa rusa a un brazo',
  'one-arm kettlebell floor press': 'Press en el suelo con pesa rusa a un brazo',
  'one-arm kettlebell jerk': 'Envión con pesa rusa a un brazo',
  'one-arm kettlebell military press to the side': 'Press militar lateral con pesa rusa a un brazo',
  'one-arm kettlebell para press': 'Press para con pesa rusa a un brazo',
  'one-arm kettlebell push press': 'Push press con pesa rusa a un brazo',
  'one-arm kettlebell snatch': 'Arrancada con pesa rusa a un brazo',
  'one-arm kettlebell split jerk': 'Envión dividido con pesa rusa a un brazo',
  'one-arm kettlebell split snatch': 'Arrancada dividida con pesa rusa a un brazo',
  'one-arm kettlebell swings': 'Balanceos con pesa rusa a un brazo',
  'one-arm medicine ball slam': 'Golpe de balón medicinal a un brazo',
  'one-arm open palm kettlebell clean': 'Cargada con palma abierta a un brazo',
  'one-arm overhead kettlebell squats': 'Sentadilla sobre la cabeza con pesa rusa a un brazo',
  'one-arm side deadlift': 'Peso muerto lateral a un brazo',
  'one-arm side laterals': 'Elevaciones laterales a un brazo',
  'one arm against wall': 'Un brazo contra la pared',
  'one arm chin-up': 'Dominada supina a un brazo',
  'one arm dumbbell preacher curl': 'Curl en banco Scott a un brazo',
  'one arm floor press': 'Press en el suelo a un brazo',
  'one arm lat pulldown': 'Jalón al pecho a un brazo',
  'one arm pronated dumbbell triceps extension': 'Extensión de tríceps pronada a un brazo',
  'one arm supinated dumbbell triceps extension': 'Extensión de tríceps supinada a un brazo',
  'one half locust': 'Media langosta',
  'one handed hang': 'Suspensión a una mano',
  'one knee to chest': 'Una rodilla al pecho',
  'one leg barbell squat': 'Sentadilla a una pierna con barra',
  'open palm kettlebell clean': 'Cargada con palma abierta',
  'otis-up': 'Abdominal Otis',
  'overhead cable curl': 'Curl sobre la cabeza en polea',
  'overhead lat': 'Dorsal sobre la cabeza',
  'overhead slam': 'Golpe sobre la cabeza',
  'overhead stretch': 'Estiramiento sobre la cabeza',
  'overhead triceps': 'Tríceps sobre la cabeza',
  'pallof press': 'Press Pallof',
  'pallof press with rotation': 'Press Pallof con rotación',
  'palms-down dumbbell wrist curl over a bench': 'Curl de muñeca pronado sobre banco',
  'palms-up barbell wrist curl over a bench': 'Curl de muñeca supinado con barra sobre banco',
  'palms-up dumbbell wrist curl over a bench': 'Curl de muñeca supinado con mancuernas sobre banco',
  'parallel bar dip': 'Fondos en paralelas',
  'peroneals-smr': 'Peroneos - liberación miofascial',
  'peroneals stretch': 'Estiramiento de peroneos',
  'physioball hip bridge': 'Puente de cadera sobre pelota suiza',
  'pin presses': 'Press contra pins',
  'piriformis-smr': 'Piriforme - liberación miofascial',
  'plate twist': 'Giro con disco',
  'platform hamstring slides': 'Deslizamientos de isquios en plataforma',
  'plie dumbbell squat': 'Sentadilla plié con mancuerna',
  'plyo kettlebell pushups': 'Flexiones pliométricas con pesa rusa',
  'plyo push-up': 'Flexión pliométrica',
  'posterior tibialis stretch': 'Estiramiento de tibial posterior',
  'power clean from blocks': 'Cargada de potencia desde bloques',
  'power jerk': 'Envión de potencia',
  'power partials': 'Parciales de potencia',
  'power snatch from blocks': 'Arrancada de potencia desde bloques',
  'power stairs': 'Escaleras de potencia',
  'preacher hammer dumbbell curl': 'Curl martillo en banco Scott',
  'prone manual hamstring': 'Isquios asistido boca abajo',
  'prowler sprint': 'Sprint con trineo',
  'pull through': 'Pull through',
  'pullups': 'Dominadas',
  'push-up wide': 'Flexión agarre ancho',
  'push-ups - close triceps position': 'Flexiones agarre cerrado',
  'push-ups with feet on an exercise ball': 'Flexiones con pies en pelota suiza',
  'push press - behind the neck': 'Push press tras nuca',
  'push up to side plank': 'Flexión a plancha lateral',
  'pushups (close and wide hand positions)': 'Flexiones (agarre cerrado y ancho)',
  'pyramid': 'Pirámide',
  'quad stretch': 'Estiramiento de cuádriceps',
  'quadriceps-smr': 'Cuádriceps - liberación miofascial',
  'quick leap': 'Salto rápido',
  'rack delivery': 'Entrega de rack',
  'rack pull with bands': 'Peso muerto desde rack con bandas',
  'rack pulls': 'Peso muerto desde rack',
  'rear leg raises': 'Elevación de pierna posterior',
  'recumbent bike': 'Bicicleta reclinada',
  'return push from stance': 'Empuje de retorno desde posición',
  'reverse band box squat': 'Sentadilla en cajón con banda inversa',
  'reverse band deadlift': 'Peso muerto con banda inversa',
  'reverse band power squat': 'Sentadilla de potencia con banda inversa',
  'reverse band sumo deadlift': 'Peso muerto sumo con banda inversa',
  'reverse barbell preacher curls': 'Curl inverso en banco Scott con barra',
  'reverse grip bent-over rows': 'Remo agarre inverso',
  'reverse grip triceps pushdown': 'Pressdown agarre inverso',
  'reverse machine flyes': 'Pájaros inversos en máquina',
  'reverse plate curls': 'Curl inverso con disco',
  'reverse triceps bench press': 'Press de tríceps inverso en banca',
  'rhomboids-smr': 'Romboides - liberación miofascial',
  'rickshaw carry': 'Caminata con rickshaw',
  'rickshaw deadlift': 'Peso muerto rickshaw',
  'ring dips': 'Fondos en anillas',
  'rocket jump': 'Salto cohete',
  'rocking standing calf raise': 'Gemelos de pie con balanceo',
  'rocky pull-ups/pulldowns': 'Dominadas/jalones Rocky',
  'romanian deadlift from deficit': 'Peso muerto rumano con déficit',
  'rope climb': 'Escalada de cuerda',
  'rope jumping': 'Saltar la cuerda',
  'rope straight-arm pulldown': 'Jalón con brazos rectos con cuerda',
  'round the world shoulder stretch': 'Estiramiento de hombros alrededor del mundo',
  'rowing, stationary': 'Remo estacionario',
  "runner's stretch": 'Estiramiento de corredor',
  'running, treadmill': 'Correr en cinta',
  'sandbag load': 'Carga de saco',
  'scissor kick': 'Tijeras',
  'scissors jump': 'Salto de tijeras',
  'seated band hamstring curl': 'Curl de isquios sentado con banda',
  'seated barbell twist': 'Giro sentado con barra',
  'seated bent-over one-arm dumbbell triceps extension': 'Extensión de tríceps sentado con un brazo',
  'seated bent-over rear delt raise': 'Pájaros sentado',
  'seated bent-over two-arm dumbbell triceps extension': 'Extensión de tríceps sentado con dos mancuernas',
  'seated biceps': 'Bíceps sentado',
  'seated cable shoulder press': 'Press de hombros sentado en polea',
  'seated calf stretch': 'Estiramiento de gemelos sentado',
  'seated close-grip concentration barbell curl': 'Curl concentrado sentado agarre cerrado',
  'seated dumbbell palms-down wrist curl': 'Curl de muñeca pronado sentado',
  'seated dumbbell palms-up wrist curl': 'Curl de muñeca supinado sentado',
  'seated flat bench leg pull-in': 'Pull-in de piernas sentado en banco',
  'seated floor hamstring stretch': 'Estiramiento de isquios sentado en el suelo',
  'seated front deltoid': 'Deltoides frontal sentado',
  'seated glute': 'Glúteo sentado',
  'seated good mornings': 'Buenos días sentado',
  'seated hamstring': 'Isquios sentado',
  'seated hamstring and calf stretch': 'Estiramiento de isquios y gemelos sentado',
  'seated head harness neck resistance': 'Resistencia de cuello con casco sentado',
  'seated leg tucks': 'Tucks de piernas sentado',
  'seated one-arm dumbbell palms-down wrist curl': 'Curl de muñeca pronado sentado a un brazo',
  'seated one-arm dumbbell palms-up wrist curl': 'Curl de muñeca supinado sentado a un brazo',
  'seated one-arm cable pulley rows': 'Remo a un brazo sentado en polea',
  'seated overhead stretch': 'Estiramiento sentado sobre la cabeza',
  'seated palm-up barbell wrist curl': 'Curl de muñeca supinado sentado con barra',
  'seated palms-down barbell wrist curl': 'Curl de muñeca pronado sentado con barra',
  'seated side lateral raise': 'Elevación lateral sentado',
  'seated two-arm palms-up low-pulley wrist curl': 'Curl de muñeca supinado sentado en polea baja',
  'see-saw press (alternating side press)': 'Press balancín',
  'shotgun row': 'Remo escopeta',
  'shoulder circles': 'Círculos de hombros',
  'shoulder press - with bands': 'Press de hombros con bandas',
  'shoulder raise': 'Elevación de hombros',
  'shoulder stretch': 'Estiramiento de hombros',
  'side-lying floor stretch': 'Estiramiento de lado en el suelo',
  'side bridge': 'Puente lateral',
  'side hop-sprint': 'Saltos con sprint lateral',
  'side jackknife': 'Navaja lateral',
  'side laterals to front raise': 'Elevaciones laterales a frontales',
  'side lying groin stretch': 'Estiramiento de ingle de lado',
  'side neck stretch': 'Estiramiento lateral de cuello',
  'side standing long jump': 'Salto largo lateral de pie',
  'side to side chins': 'Dominadas supinas lado a lado',
  'side to side box shuffle': 'Desplazamientos laterales sobre cajón',
  'single-arm linear jammer': 'Empuje lineal en landmine a un brazo',
  'single-arm push-up': 'Flexión a un brazo',
  'single-cone sprint drill': 'Sprint alrededor de un cono',
  'single-leg high box squat': 'Sentadilla a una pierna en cajón alto',
  'single-leg hop progression': 'Saltos a una pierna progresivos',
  'single-leg lateral hop': 'Salto lateral a una pierna',
  'single-leg leg extension': 'Extensión de cuádriceps a una pierna',
  'single-leg stride jump': 'Salto de zancada a una pierna',
  'single dumbbell raise': 'Elevación con una mancuerna',
  'single leg butt kick': 'Patada a glúteos a una pierna',
  'single leg glute bridge': 'Puente de glúteos a una pierna',
  'single leg push-off': 'Empuje a una pierna',
  'sit squats': 'Sentadillas de silla',
  'skating': 'Patinador',
  'sled overhead triceps extension': 'Extensión de tríceps con trineo sobre la cabeza',
  'sled push': 'Empuje de trineo',
  'sled reverse flye': 'Pájaros inversos con trineo',
  'sled row': 'Remo con trineo',
  'sledgehammer swings': 'Golpes de mazo',
  'smith incline shoulder raise': 'Elevación de hombros inclinada en Smith',
  'smith machine behind the back shrug': 'Encogimientos detrás en Smith',
  'smith machine bent over row': 'Remo en Smith',
  'smith machine decline press': 'Press declinado en Smith',
  'smith machine hang power clean': 'Cargada de potencia colgado en Smith',
  'smith machine hip raise': 'Elevación de cadera en Smith',
  'smith machine overhead shoulder press': 'Press de hombros sobre la cabeza en Smith',
  'smith machine pistol squat': 'Sentadilla pistola en Smith',
  'smith machine reverse calf raises': 'Gemelos inversos en Smith',
  'snatch balance': 'Equilibrio de arrancada',
  'snatch deadlift': 'Peso muerto de arrancada',
  'snatch pull': 'Tirón de arrancada',
  'snatch shrug': 'Encogimiento de arrancada',
  'snatch from blocks': 'Arrancada desde bloques',
  'speed band overhead triceps': 'Tríceps sobre la cabeza con banda rápida',
  'speed box squat': 'Sentadilla en cajón de velocidad',
  'speed squats': 'Sentadillas de velocidad',
  'spell caster': 'Lanzador de hechizos',
  'spider crawl': 'Arrastre de araña',
  'spinal stretch': 'Estiramiento de columna',
  'split clean': 'Cargada dividida',
  'split jerk': 'Envión dividido',
  'split jump': 'Salto dividido',
  'split snatch': 'Arrancada dividida',
  'split squat with dumbbells': 'Sentadilla dividida con mancuernas',
  'split squats': 'Sentadilla dividida',
  'squat jerk': 'Envión en sentadilla',
  'squat with bands': 'Sentadilla con bandas',
  'squat with chains': 'Sentadilla con cadenas',
  'squat with plate movers': 'Sentadilla con discos móviles',
  'squats - with bands': 'Sentadillas con bandas',
  'stairmaster': 'Escaladora',
  'standing alternating dumbbell press': 'Press alternado de pie con mancuernas',
  'standing bent-over one-arm dumbbell triceps extension': 'Extensión de tríceps de pie a un brazo',
  'standing bent-over two-arm dumbbell triceps extension': 'Extensión de tríceps de pie con dos mancuernas',
  'standing biceps cable curl': 'Curl de bíceps de pie en polea',
  'standing biceps stretch': 'Estiramiento de bíceps de pie',
  'standing bradford press': 'Press Bradford de pie',
  'standing cable chest press': 'Press de pecho de pie en polea',
  'standing cable lift': 'Elevación de pie en polea',
  'standing cable wood chop': 'Leñador en polea',
  'standing dumbbell reverse curl': 'Curl inverso de pie con mancuernas',
  'standing dumbbell straight-arm front delt raise above head': 'Elevación frontal sobre la cabeza con mancuernas',
  'standing dumbbell upright row': 'Remo vertical de pie con mancuernas',
  'standing elevated quad stretch': 'Estiramiento de cuádriceps de pie elevado',
  'standing front barbell raise over head': 'Elevación frontal sobre la cabeza con barra',
  'standing gastrocnemius calf stretch': 'Estiramiento de gastrocnemio de pie',
  'standing hamstring and calf stretch': 'Estiramiento de isquios y gemelos de pie',
  'standing hip circles': 'Círculos de cadera de pie',
  'standing hip flexors': 'Flexores de cadera de pie',
  'standing inner-biceps curl': 'Curl interno de pie',
  'standing lateral stretch': 'Estiramiento lateral de pie',
  'standing leg curl': 'Curl de piernas de pie',
  'standing long jump': 'Salto largo de pie',
  'standing low-pulley one-arm triceps extension': 'Extensión de tríceps a un brazo en polea baja',
  'standing military press': 'Press militar de pie',
  'standing olympic plate hand squeeze': 'Apretón de disco olímpico de pie',
  'standing one-arm dumbbell curl over incline bench': 'Curl a un brazo sobre banco inclinado',
  'standing one-arm dumbbell triceps extension': 'Extensión de tríceps de pie a un brazo',
  'standing overhead barbell triceps extension': 'Extensión de tríceps sobre la cabeza con barra',
  'standing palm-in one-arm dumbbell press': 'Press de pie a un brazo palma hacia dentro',
  'standing palms-in dumbbell press': 'Press de pie palmas hacia dentro',
  'standing palms-up barbell behind the back wrist curl': 'Curl de muñeca supinado detrás con barra',
  'standing pelvic tilt': 'Inclinación pélvica de pie',
  'standing soleus and achilles stretch': 'Estiramiento de sóleo y Aquiles',
  'standing towel triceps extension': 'Extensión de tríceps de pie con toalla',
  'standing two-arm overhead throw': 'Lanzamiento sobre la cabeza con dos brazos',
  'star jump': 'Salto de estrella',
  'step mill': 'Escaladora',
  'stiff-legged barbell deadlift': 'Peso muerto piernas rígidas con barra',
  'stiff-legged dumbbell deadlift': 'Peso muerto piernas rígidas con mancuernas',
  'stiff leg barbell good morning': 'Buenos días piernas rígidas con barra',
  'stomach vacuum': 'Vacío abdominal',
  'straight-arm dumbbell pullover': 'Pullover con mancuerna brazos rectos',
  'straight bar bench mid rows': 'Remo medio en banca con barra',
  'straight raises on incline bench': 'Elevaciones rectas en banco inclinado',
  'stride jump crossover': 'Salto de zancada cruzado',
  'sumo deadlift with bands': 'Peso muerto sumo con bandas',
  'sumo deadlift with chains': 'Peso muerto sumo con cadenas',
  'supine chest throw': 'Lanzamiento de pecho boca arriba',
  'supine one-arm overhead throw': 'Lanzamiento sobre la cabeza boca arriba a un brazo',
  'supine two-arm overhead throw': 'Lanzamiento sobre la cabeza boca arriba con dos brazos',
  'suspended fallout': 'Fallout suspendido',
  'suspended reverse crunch': 'Crunch inverso suspendido',
  'suspended row': 'Remo suspendido',
  'suspended split squat': 'Sentadilla dividida suspendida',
  'svend press': 'Press Svend',
  't-bar row with handle': 'Remo T con agarre',
  'tate press': 'Press Tate',
  'the straddle': 'El straddle',
  'tire flip': 'Volteo de neumático',
  'toe touchers': 'Toques de pies',
  'torso rotation': 'Rotación de torso',
  'trail running/walking': 'Correr/caminar en sendero',
  'tricep dumbbell kickback': 'Patada de tríceps con mancuerna',
  'tricep side stretch': 'Estiramiento lateral de tríceps',
  'triceps overhead extension with rope': 'Extensión de tríceps sobre la cabeza con cuerda',
  'triceps stretch': 'Estiramiento de tríceps',
  'tuck crunch': 'Crunch tuck',
  'two-arm dumbbell preacher curl': 'Curl en banco Scott con dos mancuernas',
  'two-arm kettlebell clean': 'Cargada con dos pesas rusas',
  'two-arm kettlebell jerk': 'Envión con dos pesas rusas',
  'two-arm kettlebell military press': 'Press militar con dos pesas rusas',
  'two-arm kettlebell row': 'Remo con dos pesas rusas',
  'underhand cable pulldowns': 'Jalones agarre supino en polea',
  'upper back-leg grab': 'Agarre de pierna desde la espalda',
  'upper back stretch': 'Estiramiento de espalda alta',
  'upright cable row': 'Remo vertical en polea',
  'upright row - with bands': 'Remo vertical con bandas',
  'upward stretch': 'Estiramiento hacia arriba',
  'v-bar pullup': 'Dominada con agarre V',
  'vertical swing': 'Balanceo vertical',
  'walking, treadmill': 'Caminar en cinta',
  'weighted ball hyperextension': 'Hiperextensión con balón',
  'weighted ball side bend': 'Flexión lateral con balón',
  'weighted bench dip': 'Fondos en banco con peso',
  'weighted crunches': 'Crunch con peso',
  'weighted jump squat': 'Sentadilla con salto con peso',
  'weighted pull ups': 'Dominadas con peso',
  'weighted sissy squat': 'Sissy squat con peso',
  'weighted sit-ups - with bands': 'Abdominales con bandas',
  'weighted squat': 'Sentadilla con peso',
  'wide-grip decline barbell bench press': 'Press declinado agarre ancho con barra',
  'wide-grip decline barbell pullover': 'Pullover declinado agarre ancho con barra',
  'wide-grip pulldown behind the neck': 'Jalón tras nuca agarre ancho',
  'wide stance barbell squat': 'Sentadilla con barra postura ancha',
  'wide stance stiff legs': 'Piernas rígidas postura ancha',
  'wind sprints': 'Sprints de viento',
  'windmills': 'Molinos',
  "world's greatest stretch": 'El mejor estiramiento del mundo',
  'wrist circles': 'Círculos de muñeca',
  'wrist rotations with straight bar': 'Rotaciones de muñeca con barra',
  'yoke walk': 'Caminata con yugo',
  'zercher squats': 'Sentadilla Zercher',
  'zottman preacher curl': 'Curl Zottman en banco Scott',
}

Object.assign(TRANSLATIONS, EXTRA_TRANSLATIONS)

function normalizeKey(s) {
  return (s || '').trim().toLowerCase().replace(/\s+/g, ' ')
}

const exerciseKey = (name) => TRANSLATIONS[normalizeKey(name)] || null

async function main() {
  console.log('Descargando catálogo desde free-exercise-db...')
  const res = await fetch(SOURCE)
  if (!res.ok) throw new Error(`Error HTTP ${res.status}`)
  const data = await res.json()
  console.log(`Descargados ${data.length} ejercicios`)

  const muscles = new Map()
  const equipment = new Map()
  const exercises = []

  for (const raw of data) {
    const primary = raw.primaryMuscles?.[0] ?? 'other'
    const m = MUSCLES[normalizeKey(primary)] ?? { name: raw.primaryMuscles?.[0] ?? 'Otros', group: 'otros' }
    if (!muscles.has(m.name)) muscles.set(m.name, { name: m.name, group_name: m.group })

    const eqKey = normalizeKey(raw.equipment)
    const eq = EQUIPMENT[eqKey] ?? { name: raw.equipment || 'Otros', kind: 'other' }
    if (!equipment.has(eq.name)) equipment.set(eq.name, { name: eq.name, kind: eq.kind })

    const secondary = (raw.secondaryMuscles ?? [])
      .map((s) => MUSCLES[normalizeKey(s)]?.name)
      .filter(Boolean)
      .filter((n) => n !== m.name)

    exercises.push({
      source_id: raw.id,
      name: exerciseKey(raw.name) ?? raw.name,
      name_en: raw.name,
      instructions: Array.isArray(raw.instructions) ? raw.instructions : null,
      muscle_primary: m.name,
      muscle_secondary: secondary,
      equipment: eq.name,
      category: CATEGORIES[normalizeKey(raw.category)] ?? 'fuerza',
      level: LEVELS[normalizeKey(raw.level)] ?? null,
      force: raw.force ? normalizeKey(raw.force) : null,
      image_url: raw.images?.[0] ? `${IMG_BASE}/${raw.images[0]}` : null,
    })
  }

  const output = {
    source: SOURCE,
    fetched_at: new Date().toISOString(),
    muscles: [...muscles.values()],
    equipment: [...equipment.values()],
    exercises,
  }

  await mkdir(path.dirname(OUT), { recursive: true })
  await writeFile(OUT, JSON.stringify(output, null, 2))
  console.log(`OK → supabase/seed-data.json`)
  console.log(`  Músculos: ${output.muscles.length} | Equipos: ${output.equipment.length} | Ejercicios: ${output.exercises.length}`)
}

main().catch((err) => {
  console.error('Error:', err.message)
  process.exit(1)
})